//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsync.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gsync.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered-To: drmoisan@gmail.com
        ///Received: by 2002:a05:6214:2d17:b0:6f4:c961:3b2c with SMTP id mz23csp5522017qvb;
        ///        Sat, 17 May 2025 00:00:20 -0700 (PDT)
        ///X-Google-Smtp-Source: AGHT+IFNNiF6a/FxJoh0dcqIPBdmdfcVlTCq9QRZH6N39zerQvU4lM+FFboxlMbzMdljCPYRmABi
        ///X-Received: by 2002:a05:6a20:5484:b0:1f5:8de8:3b1a with SMTP id adf61e73a8af0-2170cc65e30mr8998116637.13.1747465220506;
        ///        Sat, 17 May 2025 00:00:20 -0700 (PDT)
        ///ARC-Seal: i=1; a=rsa-sha256; t=1747465220; cv=none;
        ///        d=google.com; s=arc- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RealHeader {
            get {
                return ResourceManager.GetString("RealHeader", resourceCulture);
            }
        }
    }
}
